config/routes.rb
Abbyjones::Application.routes.draw do
  
  devise_for :admins
  get "/index", to: 'static_pages#home'
  get "/about", to: 'static_pages#about'
  get "/resume", to: 'static_pages#resume'

  root 'static_pages#home'

  resources :blogs do
    collection do
      get 'main'
      get 'teaching'
      get 'programming'
      get 'writing'
      get 'general'
    end
  end

  resources :projects do
    collection do
      get 'main'
      get 'teaching'
      get 'programming'
      get 'writing'
      get 'general'
    end
  end

  resources :resources do
    collection do
      get 'main'
      get 'teaching'
      get 'programming'
      get 'writing'
      get 'general'
    end
  end

end

app/models/blog.rb
class Blog < ActiveRecord::Base
  extend FriendlyId
  friendly_id :title, use: :slugged
  scope :published, -> (published) { where publish: published }

  def preview
    words = self.content.split(' ')
    words[0..40].join(' ') + '...' 
  end

  def self.index(admin=nil)
    if admin
      @blogs = Blog.order(created_at: :desc)
    else
      @blogs = Blog.order(created_at: :desc).where(publish: true)
    end
  end

  def self.most_recent(admin=nil)
    if admin
      @blogs = Blog.order(created_at: :desc).limit(3)
    else 
      @blogs = Blog.order(created_at: :desc).where(publish: true).limit(3)
    end
  end

  def self.by_category(category, admin=nil)
    if admin
      @blogs = Blog.where(category: category).order(created_at: :desc)
    else
      @blogs = Blog.where(category: category).published(true).order(created_at: :desc)
    end
  end

end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_admin!, only: [:new, :edit, :update, :destroy]

  # GET /blogs/main
  def main
    @blogs = Blog.most_recent(current_admin)
  end

  def teaching
    @blogs = Blog.by_category("teaching", current_admin)
  end

  def programming
    @blogs = Blog.by_category("programming", current_admin)
  end

  def writing
    @blogs = Blog.by_category("writing", current_admin)
  end

  def general
    @blogs = Blog.by_category("general", current_admin)
  end

  # GET /blogs
  def index
    @blogs = Blog.index(current_admin)
  end

  # GET /blogs/1
  def show
    if @blog.publish == false && current_admin == nil
      flash[:notice] = "The article you were looking for is not available"
      redirect_to main_blogs_path
    end
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
        format.json { render action: 'show', status: :created, location: @blog }
      else
        format.html { render action: 'new' }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_params
      params.require(:blog).permit(:title, :content, :category, :tags, :publish)
    end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/blogs/_form.html.erb
  <%= form_for(@blog) do |f| %>
    <% if @blog.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

        <ul>
        <% @blog.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <%= f.label :title %>
    <%= f.text_field :title %>

    <%= f.label :content %>
    <%= f.text_area :content %>

    <div>
      <%= f.label :category %> <br>
      <div class="radio_buttons">
        <%= f.radio_button("category", "teaching") %>
        <%= f.label :teaching %> <br>
        <%= f.radio_button("category", "programming") %>
        <%= f.label :programming %> <br>
        <%= f.radio_button("category", "writing") %>
        <%= f.label :writing %> <br>
        <%= f.radio_button("category", "general") %>
        <%= f.label :general %> <br>      
      </div>
    </div>

    <%= f.label :tags %>
    <%= f.text_field :tags %>

    <%= f.label :publish %>
    <%= f.check_box :publish %>

    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>

app/views/blogs/_previews.html.erb
<br>
<% @blogs.each do |blog| %>
  <h3> <%= link_to "#{blog.title}", blog %> </h3>
  <p> <%= markdown blog.preview %> </p>
  <%= link_to "More...", blog %>
  <br>
  <hr>
<% end %>

app/views/blogs/_sidebar.html.erb
<div class="medium-3 medium-offset-1 columns">

  <h2> Categories </h2>
  <ul>
    <li> <%= link_to "Programming", programming_blogs_path %> </li>
    <li> <%= link_to "Teaching", teaching_blogs_path %> </li>
    <li> <%= link_to "Writing", writing_blogs_path %> </li>
    <li> <%= link_to "General",  general_blogs_path %> </li>  
    <li> <%= link_to "All",  blogs_path %> </li>        
  </ul>

  <% if admin_signed_in? %>
    <hr>
    <%= link_to "Create New", new_blog_path, :class => "button" %>
  <% end %>


</div>

app/views/blogs/edit.html.erb
<div class="row">
  <h1>Editing blog</h1>

  <%= render 'form' %>

  <%= link_to 'Show', @blog %> |
  <%= link_to 'Back', blogs_path %>
</div>

app/views/blogs/general.html.erb
<div class="row panel">
  <div class="medium-8 columns">
    <h1> General Articles </h1>
    <%= render 'previews' %>
  </div>

  <%= render 'sidebar' %>
</div>

app/views/blogs/index.html.erb
<div class="row panel">
  
  <div class="medium-8 columns">
    <h1>All Posts</h1>
    <%= render "previews" %>
  </div>

  <%= render "sidebar" %>

</div>

app/views/blogs/main.html.erb
<div class="row panel">

  <div class="medium-8 columns">
    <h1> Newest Posts </h1>
    <%= render 'previews' %>
    <br>
    <%= link_to "See all posts", blogs_path %>

  </div>

  <%= render 'sidebar' %>


</div>

app/views/blogs/new.html.erb
<div class="row">
  <h1>New blog</h1>

  <%= render 'form' %>

  <%= link_to 'Back', blogs_path %>
</div>

app/views/blogs/programming.html.erb
<div class="row panel">
  <div class="medium-8 columns">
    <h1> Programming Blog </h1>
    <%= render 'previews' %>
  </div>

  <%= render 'sidebar' %>
</div>

app/views/blogs/show.html.erb
<div class="row panel">

  <div class="medium-8 columns">
    <h2> <%= @blog.title %> </h2>
    <br>

    <div> <%= markdown @blog.content %> </div>
    <%= link_to 'Back', request.referer %>

    <%= render partial: "shared/admin_links", 
               locals: { controller: "blogs", resource: @blog } %>    

  </div>
  
  <%= render 'sidebar' %>

</div>

app/views/blogs/teaching.html.erb
<div class="row panel">
  <div class="medium-8 columns">
    <h1> Teaching Blog </h1>
    <%= render 'previews' %>
  </div>

  <%= render 'sidebar' %>
</div>

app/views/blogs/writing.html.erb
<div class="row panel">
  <div class="medium-8 columns">
    <h1> Writing Blog</h1>
    <%= render 'previews' %>
  </div>

  <%= render 'sidebar' %>
</div>