config/routes.rb
Abbyjones::Application.routes.draw do
  
  devise_for :admins
  get "/index", to: 'static_pages#home'
  get "/about", to: 'static_pages#about'
  get "/resume", to: 'static_pages#resume'

  root 'static_pages#home'

  resources :blogs do
    collection do
      get 'main'
      get 'teaching'
      get 'programming'
      get 'writing'
      get 'general'
    end
  end

  resources :projects do
    collection do
      get 'main'
      get 'teaching'
      get 'programming'
      get 'writing'
      get 'general'
    end
  end

  resources :resources do
    collection do
      get 'main'
      get 'teaching'
      get 'programming'
      get 'writing'
      get 'general'
    end
  end

end

app/models/project.rb
class Project < ActiveRecord::Base
  has_attached_file :screenshot, :styles => { :medium => "300x300>", :thumb => "100x100>" }
  validates_attachment_content_type :screenshot, :content_type => /\Aimage\/.*\Z/
  validates_attachment_file_name :screenshot, :matches => [/png\Z/i, /jpe?g\Z/i]
  validates :date, presence: true
  validates :category, presence: true 

  extend FriendlyId
  friendly_id :title, use: :slugged

  def preview
    words = self.description.split(' ')
    words[0..40].join(' ') + '...' 
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_admin!, only: [:new, :edit, :update, :destroy]

  def main
    @projects = Project.order(date: :desc).limit(3)
  end

  def teaching
    @projects = Project.where(category: "teaching").order(date: :desc)
  end

  def programming
    @projects = Project.where(category: "programming").order(date: :desc)
  end

  def writing
    @projects = Project.where(category: "writing").order(date: :desc)
  end

  def general
    @projects = Project.where(category: "general").order(date: :desc)
  end

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.order(date: :desc)
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render action: 'show', status: :created, location: @project }
      else
        format.html { render action: 'new' }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:title, :link, :date, :description,
        :category, :status, :screenshot)
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :link %><br>
    <%= f.text_field :link %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.text_field :date %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description, :class => "tinymce" %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.text_field :status %>
  </div>
  <div>
      <%= f.label :category %> <br>
      <div class="radio_buttons">
        <%= f.radio_button("category", "teaching") %>
        <%= f.label :teaching %> <br>
        <%= f.radio_button("category", "programming") %>
        <%= f.label :programming %> <br>
        <%= f.radio_button("category", "writing") %>
        <%= f.label :writing %> <br>
        <%= f.radio_button("category", "general") %>
        <%= f.label :general %> <br>      
      </div>
    </div>
    <div class="field">
      <%= f.label :screenshot %><br>
      <%= f.file_field :screenshot %>
    </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/_show_projects.html.erb
<br>
<% @projects.each do |project| %>
  <div class="row">
    <% if project.screenshot_file_name != nil %>
      <%= image_tag project.screenshot.url(:medium), alt: "#{project.title}", 
        :class => "medium-4 columns text-center" %>
    <% end %>
    <div class="medium-8 columns">
      <h3> <%= link_to "#{project.title}", project %> </h3>
      <p> <%= project.preview.html_safe %> </p>
      <%= link_to "More...", project %>
      <br><br>
    </div>
    <br>
    <hr>
  </div>
<% end %>

app/views/projects/_sidebar.html.erb
<div class="medium-3 medium-offset-1 columns">

  <h2> Categories </h2>
  <ul>
    <li> <%= link_to "Programming", programming_projects_path %> </li>
    <li> <%= link_to "Teaching", teaching_projects_path %> </li>
    <li> <%= link_to "Writing", writing_projects_path %> </li>
    <li> <%= link_to "General",  general_projects_path %> </li>  
    <li> <%= link_to "All",  projects_path %> </li>        
  </ul>

  <% if admin_signed_in? %>
    <hr>
    <%= link_to "Create New", new_project_path, :class => "button" %>
  <% end %>


</div>

app/views/projects/edit.html.erb
<div class="row">
  <h1>Editing project</h1>

  <%= render 'form' %>

  <%= link_to 'Show', @project %> |
  <%= link_to 'Back', projects_path %>
</div>

app/views/projects/general.html.erb
<div class="row panel">
  <div class="medium-8 columns">
    <h1> Other Projects </h1>
    <%= render 'show_projects' %>
  </div>

  <%= render 'sidebar' %>
</div>

app/views/projects/index.html.erb
<div class="row panel">
  <div class="medium-8 columns">
    <h1>All Projects</h1>
    <%= render "show_projects" %>   
  </div>

  <%= render "sidebar" %>
</div>

app/views/projects/main.html.erb
<div class="row panel">
  <div class="medium-8 columns">
    <h1> Newest Projects </h1>
    <%= render 'show_projects' %>
  </div>

  <%= render 'sidebar' %>
</div>

app/views/projects/new.html.erb
<div class="row">
  <h1>New project</h1>
  <%= render 'form' %>
  <%= link_to 'Back', projects_path %>
</div>

app/views/projects/programming.html.erb
<div class="row panel">
  <div class="medium-8 columns">
    <h1> Programming Projects </h1>
    <%= render 'show_projects' %>
  </div>

  <%= render 'sidebar' %>
</div>

app/views/projects/show.html.erb
<div class="row panel">
  <div class="medium-8 columns">
    <h1> Project: <%= @project.title %> </h1>
      <% if @project.screenshot_file_name != nil %>
        <%= image_tag @project.screenshot.url, alt: "#{@project.title} screenshot" %>
      <% end %>
      <p> <%= @project.description.html_safe %> </p>
      <p> <%= link_to "#{@project.link}", @project.link %> </p>
      <p> Category: <%= @project.category.capitalize %> </p>
    <br>
    <%= link_to 'Back', request.referer %>

    <%= render partial: "shared/admin_links", 
               locals: { controller: "projects", resource: @project } %>

  </div>


  <%= render 'sidebar' %>
</div>

app/views/projects/teaching.html.erb
<div class="row panel">
  <div class="medium-8 columns">
    <h1> Teaching Projects </h1>
    <%= render 'show_projects' %>
  </div>

  <%= render 'sidebar' %>
</div>

app/views/projects/writing.html.erb
<div class="row panel">
  <div class="medium-8 columns">
    <h1> Writing Projects </h1>
    <%= render 'show_projects' %>
  </div>

  <%= render 'sidebar' %>
</div>