config/routes.rb
Abbyjones::Application.routes.draw do
  
  devise_for :admins
  get "/index", to: 'static_pages#home'
  get "/about", to: 'static_pages#about'
  get "/resume", to: 'static_pages#resume'

  root 'static_pages#home'

  resources :blogs do
    collection do
      get 'main'
      get 'teaching'
      get 'programming'
      get 'writing'
      get 'general'
    end
  end

  resources :projects do
    collection do
      get 'main'
      get 'teaching'
      get 'programming'
      get 'writing'
      get 'general'
    end
  end

  resources :resources do
    collection do
      get 'main'
      get 'teaching'
      get 'programming'
      get 'writing'
      get 'general'
    end
  end

end

app/views/resources/_form.html.erb
  <%= form_for(@resource) do |f| %>
    <% if @resource.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@resource.errors.count, "error") %> prohibited this resource from being saved:</h2>

        <ul>
        <% @resource.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= f.label :title %><br>
      <%= f.text_field :title %>
    </div>
    <div class="field">
      <%= f.label :description %><br>
      <%= f.text_area :description %>
    </div>
    <div class="field">
      <%= f.label :link %><br>
      <%= f.text_field :link %>
    </div>
    <div>
      <%= f.label :category %> <br>
      <div class="radio_buttons">
        <%= f.radio_button("category", "teaching") %>
        <%= f.label :teaching %> <br>
        <%= f.radio_button("category", "programming") %>
        <%= f.label :programming %> <br>
        <%= f.radio_button("category", "writing") %>
        <%= f.label :writing %> <br>
        <%= f.radio_button("category", "general") %>
        <%= f.label :general %> <br>      
      </div>
    </div>
    <div class="field">
      <%= f.label :tags %><br>
      <%= f.text_field :tags %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>

app/views/resources/_previews.html.erb
<br>
<% @resources.each do |resource| %>
  <h3> <%= link_to "#{resource.title}", resource %> </h3>
  <p> <%= markdown resource.preview %> </p>
  <%= link_to "More...", resource %>
  <br>
  <hr>
<% end %>

app/views/resources/_show_resources.html.erb
<br>
<% @resources.each do |resource| %>
  <h3><%= link_to resource.title, resource %> </h3>
  <p><%= markdown resource.preview %></p>
  <p> <em>Tags:</em> <%= resource.tags %> </p>
  <%= link_to "Learn More...", resource %>
  <br>
  <br>
  <hr>
<% end %>

app/views/resources/_sidebar.html.erb
<div class="medium-3 medium-offset-1 columns">

  <h2> Categories </h2>
  <ul>
    <li> <%= link_to "Programming", programming_resources_path %> </li>
    <li> <%= link_to "Teaching", teaching_resources_path %> </li>
    <li> <%= link_to "Writing", writing_resources_path %> </li>
    <li> <%= link_to "General",  general_resources_path %> </li>  
    <li> <%= link_to "All",  resources_path %> </li>        
  </ul>

  <% if admin_signed_in? %>
    <hr>
    <%= link_to "Create New", new_resource_path, :class => "button" %>
  <% end %>


</div>

app/views/resources/edit.html.erb
<div class="row">
  <h1>Editing resource</h1>

  <%= render 'form' %>

  <%= link_to 'Show', @resource %> |
  <%= link_to 'Back', resources_path %>
</div>

app/views/resources/general.html.erb
<div class="row panel">
  <div class="medium-8 columns">
    <h1> General Resources </h1>
    <%= render 'show_resources' %>
  </div>

  <%= render 'sidebar' %>
</div>

app/views/resources/index.html.erb
<div class="row panel">
  <div class="medium-8 columns">
    <h1>Resource Index</h1>
    <%= render "show_resources" %> 
    
    <% if current_admin %>
      <br>
      <%= link_to 'New Resource', new_resource_path %>
    <% end %>
  </div>
  
  <%= render "sidebar" %>
</div>

app/views/resources/main.html.erb
<div class="row panel">
  <div class="medium-8 columns">
    <h1> Newest Resources </h1>
    <%= render 'show_resources' %>
  </div>

  <%= render 'sidebar' %>
</div>

app/views/resources/new.html.erb
<div class="row">
  <h1>New resource</h1>

  <%= render 'form' %>

  <%= link_to 'Back', resources_path %>
</div>

app/views/resources/programming.html.erb
<div class="row panel">
  <div class="medium-8 columns">
    <h1> Programming Resources </h1>
    <%= render 'show_resources' %>
  </div>

  <%= render 'sidebar' %>
</div>

app/views/resources/show.html.erb
<div class="row panel">
  <div class="medium-8 columns">
    <h1>
      <%= @resource.title %>
    </h1>

    <hr>

    <p>
      <%= @resource.description.html_safe %>
    </p>

    <p>
      <%= link_to @resource.link, @resource.link %>
    </p>

    <p>
      <strong>Tags:</strong>
      <%= @resource.tags %>
    </p>

    <p>
      <strong>Category:</strong>
      <%= @resource.category.capitalize %>
    </p>

    <%= link_to 'Back', request.referer %>

    <%= render partial: "shared/admin_links", 
               locals: { controller: "resources", resource: @resource } %>

  </div>

  <%= render 'sidebar' %>
</div>

app/views/resources/teaching.html.erb
<div class="row panel">
  <div class="medium-8 columns">
    <h1> Teaching Resources </h1>
    <%= render 'show_resources' %>
  </div>

  <%= render 'sidebar' %>
</div>

app/views/resources/writing.html.erb
<div class="row panel">
  <div class="medium-8 columns">
    <h1> Writing Resources </h1>
    <%= render 'show_resources' %>
  </div>

  <%= render 'sidebar' %>
</div>