config/routes.rb
Abbyjones::Application.routes.draw do
  
  devise_for :admins
  get "/index", to: 'static_pages#home'
  get "/about", to: 'static_pages#about'
  get "/resume", to: 'static_pages#resume'

  root 'static_pages#home'

  resources :blogs do
    collection do
      get 'main'
      get 'teaching'
      get 'programming'
      get 'writing'
      get 'general'
    end
  end

  resources :projects do
    collection do
      get 'main'
      get 'teaching'
      get 'programming'
      get 'writing'
      get 'general'
    end
  end

  resources :resources do
    collection do
      get 'main'
      get 'teaching'
      get 'programming'
      get 'writing'
      get 'general'
    end
  end

end

app/views/layouts/_ga.html.erb
<!-- Google Analytics Tracking Snippet -->
<!-- Only load it if we're in a production environment! -->
  
  
<% if Rails.env.production? %>

  <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-44000602-2', 'auto');
    ga('send', 'pageview');
  </script>

<% end %>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Zurb Foundation %>
<div class="row">
  <% flash.each do |name, msg| %>
    <% if msg.is_a?(String) %>
      <div data-alert class="alert-box round <%= name.to_s == 'notice' ? 'success' : 'alert' %>">
        <%= content_tag :div, msg %>
        <a href="#" class="close">&times;</a>
      </div>
    <% end %>
  <% end %>
</div>

app/views/layouts/_navigation.html.erb
<nav class="top-bar sticky medium-12 columns" data-topbar>
  <ul class="title-area">
    <li class="name">
      <h1><a href="/">Home</a></h1>
    </li>
    <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
    <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
  </ul>
  <section class="top-bar-section">
    <!-- Right Nav Section -->
    <ul class="right">
      <li><a href="/about"> About </a></li>
      <li><%= link_to "Projects", main_projects_path %></li>
      <li><%= link_to "Blog", main_blogs_path %></li>
      <li><%= link_to "Resources", main_resources_path %></li>
      <li><a href="/resume"> Resume </a></li>

      <% if admin_signed_in? %>
        <li> <%= link_to "Logout", destroy_admin_session_path, method: :delete %> </li>
      <% end %>
    </ul>
  </section>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "AbbyJones" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>

    <%= render 'layouts/ga' %> 
  </head>

  <body> 
  <div class="background-wrapper">
    <header class="row">
      <h1 class="text-center">Abby Jones</h1>
      <h2 class="text-center"> <small> ...adventure in progress... </small> </h2>
      <%= render 'layouts/navigation' %>
    </header>

    <%= render 'layouts/messages' %>
    
    <%= yield %>
    

    <footer>
      <div class="row contact text-center">
        <a href="mailto:contact@abbyjones.net" class="button small radius"> Email </a>
        <a href="http://twitter.com/AbbyJones80" class="button small radius"> Twitter </a>
        <a href="http://github.com/AbbyJonesDev" class="button small radius"> GitHub </a>
        <a href="http://www.linkedin.com/pub/abigail-jones/60/1a8/230/" class="button small radius"> LinkedIn </a> 
      </div>
      <div class="row">
        <% unless admin_signed_in? %>
          <%= link_to "Login", new_admin_session_path %>
        <% end %>
      </div>
    </footer>

  </div> <!-- Background wrapper -->
  <%= javascript_include_tag "application" %>
  </body>
</html>